name: CI-GCC


on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    run-gcc:
        runs-on: ubuntu-latest
        steps:
          - name: Check Setup
            uses: egor-tensin/setup-gcc@v1
            with:
                version: latest
                platform: x64
                cc: gcc
          - name: install gcc
            run: |
             sudo apt update
             sudo apt-get install gcc
          - name: Configuretion gcc file
            run: |
              gcc hello.c -o hello
          - name: Run the Compiled Program
            run: |
              ./hello
